#!/bin/sh

if [ -d "/var/lib/itsmbackup_update" ]
then
    echo "Restore old ITSM-NG files..."
    cp -r /var/lib/itsmbackup_update/files/* /var/lib/itsm-ng/
    echo "Restore old ITSM-NG config..."
    cp -r /var/lib/itsmbackup_update/config/* /etc
    echo "Restore old ITSM-NG plugins..."
    cp -r /var/lib/itsmbackup_update/plugins /usr/share/itsm-ng/
    
    if [ -f "/var/lib/itsmbackup_update/itsm-ng.conf" ]
    then
        echo "Restore ITSM-NG apache configuration file"
        cp -r /var/lib/itsmbackup_update/itsm-ng.conf /etc/apache2/sites-available/
    fi

    echo "Remove ITSM-NG backup folder"
    rm -rf /var/lib/itsmbackup_update
else 
    echo "No old files or folders to restore"
fi

if [ -e "/usr/sbin/apache2" ]; then
    a2ensite itsm-ng.conf
    service apache2 reload
fi


chown -R www-data:www-data /etc/itsm-ng
chown -R www-data:www-data /usr/share/itsm-ng
chown -R www-data:www-data /var/lib/itsm-ng
chown -R www-data:www-data /var/log/itsm-ng

exit 0
