#!/bin/sh
#set -e

echo "Clean old version"

if [ -d "/var/www/html/itsm-ng/config" ]
then
    rm -rf /var/www/html/itsm-ng/config /var/www/html/itsm-ng/files
fi

if [ -d "/var/www/html/itsm-ng/files" ]
then
    rm -rf /var/www/html/itsm-ng/files
fi

if [ -e "/usr/sbin/apache2" ]; then
    a2dissite itsm-ng.conf
    service apache2 reload
fi
exit 0